const buildings = {
    // basic
    'mayor_house': {
        name: 'Mayor\'s house',
        level: 0,
        icon: 'https://settlersonlinewiki.eu/budynek/ratusz.png',
        perLevel: [
            {
                cost: [],
                gem: 0,
                duration: 0,
                image: 'https://settlersonlinewiki.eu/budynek/ratusz1.png',
                storage: 500,
            },
            {
                cost: [['hardwood_plank', 800], ['marble', 450]],
                gem: 1226,
                duration: 2.5 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/ratusz2.png',
                storage: 1600,
            },
            {
                cost: [['coin', 400], ['marble', 450]],
                gem: 1766,
                duration: 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/ratusz3.png',
                storage: 1500,
            },
            {
                cost: [['exotic_wood_plank', 750], ['coin', 900]],
                gem: 3908,
                duration: 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/ratusz4.png',
                storage: 3000,
            },
            {
                cost: [['exotic_wood_plank', 1500], ['granite', 1800]],
                gem: 5371,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/ratusz5.png',
                storage: 4000,
            },
            {
                cost: [['grout', 600], ['granite', 3000]],
                amount2: 3000,
                gem: 6993,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/ratusz6.png',
                storage: 5900,
            },
            {
                cost: [['advanced_tool', 3400], ['oil', 2750]],
                gem: 5535,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/ratusz7.png',
                storage: 9000
            },
        ]
    },
    'pinewood_cutter': {
        name: 'Pinewood Cutter',
        level: 1,
        icon: 'https://settlersonlinewiki.eu/images/drwal0.png',
        needLicense: true,
        production: {
            time: 1.5 * 60,
            input: [
                { item: 'pinewood_deposit', amount: 1 },
            ],
            output: [
                { item: 'pinewood', amount: 1 },
            ],
        },
        perLevel: [
            {
                cost: [],
                moveCost: [['pinewood_plank', 2], ['stone', 2]],
                gem: 2,
                moveGem: 1,
                duration: 10,
                image: 'https://settlersonlinewiki.eu/budynek/drwal1.png',
            },
            {
                cost: [['hardwood_plank', 120], ['marble', 100]],
                moveCost: [['pinewood_plank', 40], ['stone', 40]],
                gem: 221,
                moveGem: 2,
                duration: 2.5 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/drwal2.png',
            },
            {
                cost: [['hardwood_plank', 300], ['marble', 150]],
                moveCost: [['hardwood_plank', 100], ['stone', 75]],
                gem: 439,
                moveGem: 7,
                duration: 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/drwal3.png',
            },
            {
                cost: [['coin', 500], ['marble', 300]],
                moveCost: [['hardwood_plank', 100], ['marble', 100]],
                gem: 1913,
                moveGem: 11,
                duration: 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/drwal4.png',
            },
            {
                cost: [['exotic_wood_plank', 500], ['granite', 300]],
                moveCost: [['coin', 100], ['marble', 200]],
                gem: 1253,
                moveGem: 29,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/drwal5.png',
            },
            {
                cost: [['grout', 50], ['granite', 500]],
                moveCost: [['coin', 100], ['marble', 200]],
                gem: 1031,
                moveGem: 29,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/drwal6.png',
            },
            {
                cost: [['advanced_tool', 500], ['oil', 250]],
                moveCost: [['coin', 200], ['marble', 300]],
                gem: 675,
                moveGem: 53,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/drwal7.png',
            },
        ],
    },
    'pinewood_sawmill': {
        name: 'Pinewood Sawmill',
        level: 2,
        icon: 'https://settlersonlinewiki.eu/images/tartakigla0.png',
        needLicense: true,
        production: {
            time: 3 * 60,
            input: [
                { item: 'pinewood', amount: 1 },
            ],
            output: [
                { item: 'pinewood_plank', amount: 1 },
            ],
        },
        perLevel: [
            {
                cost: [['pinewood', 10]],
                moveCost: [['pinewood_plank', 2], ['stone', 2]],
                gem: 2,
                moveGem: 1,
                duration: 10,
                image: 'https://settlersonlinewiki.eu/budynek/tartakigla1.png',
            },
            {
                cost: [['hardwood_plank', 120], ['marble', 100]],
                moveCost: [['pinewood_plank', 40], ['stone', 40]],
                gem: 221,
                moveGem: 2,
                duration: 2.5 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/tartakigla2.png',
            },
            {
                cost: [['hardwood_plank', 300], ['marble', 150]],
                moveCost: [['hardwood_plank', 100], ['stone', 75]],
                gem: 439,
                moveGem: 7,
                duration: 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/tartakigla3.png',
            },
            {
                cost: [['coin', 500], ['marble', 300]],
                moveCost: [['hardwood_plank', 100], ['marble', 100]],
                gem: 1913,
                moveGem: 11,
                duration: 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/tartakigla4.png',
            },
            {
                cost: [['exotic_wood_plank', 500], ['granite', 300]],
                moveCost: [['coin', 100], ['marble', 200]],
                gem: 1253,
                moveGem: 29,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/tartakigla5.png',
            },
            {
                cost: [['grout', 50], ['granite', 500]],
                moveCost: [['coin', 100], ['marble', 200]],
                gem: 1031,
                moveGem: 29,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/tartakigla6.png',
            },
            {
                cost: [['advanced_tool', 500], ['oil', 200]],
                moveCost: [['coin', 200], ['marble', 300]],
                gem: 630,
                moveGem: 53,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/tartakigla7.png',
            },
        ]
    },
    'pinewood_forester': {
        name: 'Pinewood Forester',
        level: 3,
        icon: 'https://settlersonlinewiki.eu/images/lesnikigla0.png',
        needLicense: true,
        production: {
            time: 2 * 60 + 15,
            output: [
                { item: 'pinewood_deposit', amount: 1 },
            ],
        },
        perLevel: [
            {
                cost: [['pinewood_plank', 10]],
                moveCost: [['pinewood_plank', 2], ['stone', 2]],
                gem: 2,
                moveGem: 1,
                duration: 10,
                image: 'https://settlersonlinewiki.eu/budynek/lesnikigla1.png',
            },
            {
                cost: [['hardwood_plank', 120], ['marble', 100]],
                moveCost: [['pinewood_plank', 40], ['stone', 40]],
                gem: 221,
                moveGem: 2,
                duration: 2.5 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/lesnikigla2.png',
            },
            {
                cost: [['hardwood_plank', 300], ['marble', 150]],
                moveCost: [['hardwood_plank', 100], ['stone', 75]],
                gem: 439,
                moveGem: 7,
                duration: 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/lesnikigla3.png',
            },
            {
                cost: [['coin', 500], ['marble', 300]],
                moveCost: [['hardwood_plank', 100], ['marble', 100]],
                gem: 1913,
                moveGem: 11,
                duration: 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/lesnikigla4.png',
            },
            {
                cost: [['exotic_wood_plank', 500], ['granite', 300]],
                moveCost: [['coin', 100], ['marble', 200]],
                gem: 1253,
                moveGem: 29,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/lesnikigla5.png',
            },
            {
                cost: [['grout', 50], ['granite', 500]],
                moveCost: [['coin', 100], ['marble', 200]],
                gem: 1031,
                moveGem: 29,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/lesnikigla6.png',
            },
            {
                cost: [['advanced_tool', 500], ['oil', 300]],
                moveCost: [['coin', 200], ['marble', 300]],
                gem: 720,
                moveGem: 53,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/tartakigla7.png',
            },
        ]
    },
    'tavern': {
        name: 'Tavern',
        level: 4,
        icon: 'https://settlersonlinewiki.eu/images/tawerna0.png',
        needLicense: true,
        perLevel: [
            {
                cost: [['pinewood_plank', 100]],
                moveCost: [['pinewood_plank', 30], ['stone', 20]],
                gem: 10,
                moveGem: 1,
                duration: 10*60,
                image: 'https://settlersonlinewiki.eu/budynek/tawerna1.png',
            },
        ]
    },
    'mason': {
        name: 'Mason',
        level: 5,
        icon: 'https://settlersonlinewiki.eu/images/kamieniolom0.png',
        needLicense: true,
        production: {
            time: 5 * 60,
            input: [
                { item: 'stone_deposit', amount: 1 },
            ],
            output: [
                { item: 'stone', amount: 1 },
            ],
        },
        perLevel: [
            {
                cost: [['pinewood_plank', 40]],
                moveCost: [['pinewood_plank', 6], ['stone', 6]],
                gem: 2,
                moveGem: 1,
                duration: 10,
                image: 'https://settlersonlinewiki.eu/budynek/kamieniolom1.png',
            },
            {
                cost: [['hardwood_plank', 120], ['marble', 100]],
                moveCost: [['pinewood_plank', 40], ['stone', 40]],
                gem: 221,
                moveGem: 2,
                duration: 2.5 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/kamieniolom2.png',
            },
            {
                cost: [['hardwood_plank', 300], ['marble', 150]],
                moveCost: [['hardwood_plank', 100], ['stone', 75]],
                gem: 439,
                moveGem: 7,
                duration: 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/kamieniolom3.png',
            },
            {
                cost: [['coin', 500], ['marble', 300]],
                moveCost: [['hardwood_plank', 100], ['marble', 100]],
                gem: 1913,
                moveGem: 11,
                duration: 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/kamieniolom4.png',
            },
            {
                cost: [['exotic_wood_plank', 500], ['granite', 300]],
                moveCost: [['coin', 100], ['marble', 200]],
                gem: 2061,
                moveGem: 29,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/kamieniolom5.png',
            },
            {
                cost: [['grout', 50], ['granite', 500]],
                moveCost: [['coin', 100], ['marble', 200]],
                gem: 1253,
                moveGem: 29,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/kamieniolom6.png',
            },
            {
                cost: [['advanced_tool', 500], ['oil', 200]],
                moveCost: [['coin', 200], ['marble', 300]],
                gem: 630,
                moveGem: 53,
                duration: 7 * 24  * 60 * 60,
                image: 'https://settlersonlinewiki.eu/budynek/kamieniolom7.png',
            },
        ]
    },

};